template:
  normalize_lockfiles: true
  normalize_lockfiles_command: bundle update nomono --bundler

release:
  target_branches:
    - r1_8-even-v0
    - r1_9-even-v2
    - r2_0-even-v4
    - r2_1-even-v6
    - r2_2-even-v8
    - r2_3-even-v10
    - r2_4-even-v12
    - r2_5-even-v14
    - r2_6-even-v16
    - r2_7-even-v18
    - r3_0-even-v20
    - r3_1-even-v22
    - r3_2-even-v24
    - main
