inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-lts: rubocop-lts.yml

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

###################################################################
# Rules that allow preservation of ruby 1.8.7 / ree compatibility #
###################################################################
# Required to match the rubocop-ruby1_8.yml config so run passes  #
#   regardless of which is used against this project              #
###################################################################

Style/Documentation:
  Enabled: false

# Ruby 1.8.7 needs the . on chain of method calls at the end of a line
Style/DotPosition:
  EnforcedStyle: trailing

Style/FrozenStringLiteralComment:
  Enabled: true

# Ruby 1.8.7 doesn't have 1.9 style hash syntax
Style/HashSyntax:
  EnforcedStyle: hash_rockets

# Ruby 1.8.7 doesn't have the -> lambda
Style/Lambda:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
