inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-lts: rubocop-lts.yml

require:
  - rubocop-md
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
