inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-lts: rubocop-lts.yml

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
